-- Retired as a product migration.
--
-- The previous revision deleted profile content cards with corpus-specific
-- wording learned from one validation pack. Generic ingestion must not encode
-- document/category vocabulary in SQL migrations, because each deployment can
-- contain arbitrary domains and languages.
--
-- Future cleanup should be handled by generic scoring/versioned profile
-- regeneration, not by destructive global DELETE statements.
