-- Retired as a product migration.
--
-- The previous revision pruned content cards using domain/procedure vocabulary.
-- That is not safe for arbitrary enterprise corpora and languages. Keep this
-- migration as a no-op placeholder so migration ordering stays stable.
