-- Retired as a product migration.
--
-- Layout/noise pruning belongs in generic extraction-quality scoring and
-- profile regeneration. This migration remains intentionally empty to avoid
-- destructive corpus-specific cleanup on fresh installs.
