-- Retired as a product migration.
--
-- The previous revision used action words from one corpus to delete profile
-- cards globally. Runtime ingestion must stay domain-neutral; low-signal cards
-- should be handled by generic ranking/scoring and versioned regeneration.
